#!/usr/bin/env bash
# Displays information about subdomains.

# Uncomment for debugging purposes.
# set -x

# Colors
blue='\e[1;34m'
brown='\e[0;33m'
reset='\033[0m'

# Variables
subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

# Function to display information for a given subdomain
dig_cmd () {
    local sub="$2"
    local INFO=$(dig "$sub.$domain" +short)

    if [ -n "$INFO" ]; then
        local IP=$(echo "$INFO" | awk 'NR==1')
        local RECORD=$(echo "$INFO" | awk 'NR==2')
        echo -e "${brown}The subdomain ${blue}$sub${brown} is a ${blue}$RECORD${brown} record and points to ${blue}$IP${reset}"
    else
        echo -e "${brown}Unable to resolve subdomain ${blue}$sub${reset}"
    fi
}

# Main
if [ $# -eq 1 ]; then
    for subs in "${subdomains[@]}"; do
        dig_cmd "$domain" "$subs"
    done
elif [ $# -eq 2 ]; then
    dig_cmd "$domain" "$sub"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
