#!/bin/bash
WATER="ewwatratewa"
STIR="ti.itirtrtr"
RESULT=$(echo $WATER | tr water 01234 | tr stir 56789 | tr behlnort 01234567 | tr '01234567' '0123456789abcdef' | tr '0123456789abcdef' 'gtaio luSnemf')
echo $RESULT
