#!/bin/bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo sed -i '/^frontend main$/,/^$/d' /etc/haproxy/haproxy.cfg
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT

frontend main
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOT

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

echo "HAProxy installed and configured successfully."
