#!/usr/bin/env bash

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
fi

# Install UFW
apt-get update
apt-get install ufw -y

# Enable UFW
ufw --force enable

# Reset rules
ufw --force reset

# Set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH, HTTPS, and HTTP
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

# Display status
ufw status verbose
