#!/usr/bin/env bash

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
fi

# Update package lists
apt-get update

# Install UFW
apt-get install ufw -y

# Enable IPv6
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Enable UFW and set defaults
ufw disable
ufw logging on
ufw default deny incoming
ufw default allow outgoing
ufw enable

# Allow specific ports
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
